### ISSUE TITLE
[Feature] Build LLVM/clang on AppVeyor

### ISSUE THREAD

**Issue by escherstair** [open62541/open62541#2116]
Description
I see that open62541 uses Travis and AppVeyor to build for several configurations.
Travis builds with LLVM/clang on Linux (too).
AppVeyor buils with several MS VS compilers and MinGW, so it's more MS Windows-oriented.

I'm not an expert, so I wonder if it's possible to add an extra configuration to AppVeyor to build using LLVM/clang in a MS Windows environment.

My request arises becuase I've been using clang under Windows and it happens that I see some minor issues (basically with some #define and #include)
Maybe it's possible, maybe it's not.
It's only an idea.

Background Information / Reproduction Steps
===========================================

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): 0.3-rc2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Windows 7 SP1 x64
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
Thank you for your idea!
Yes, that would be possible

Basically, the steps you would need to do:
1. Read through https://www.appveyor.com/docs/lang/cpp/ as it describes that Appveyor has LLVM/clang available
2. Update the Appveyor Build Script to use clang instead of msbuild: https://github.com/open62541/open62541/blob/master/tools/appveyor/build.ps1
3. Test it on your own repository
4. Create a Pull Request

Since implementing other features have currently higher priority, we are happy for any pull request which adds this feature. Feel free to create one and we can then discuss your changes based on that.

**Comment by escherstair** [comment]
I'll try to help somehow (even if I'm not an expert at all).
I'm going to search for some documentation and working LLVM/clang builds on AppVeyor and see what I can do.
If someone can help it would be great.

**Comment by jpfr** [comment]
Great! You can add a PR whenever ready.
And we will restart the Appveyor build as often as necessary. 😄

**Comment by escherstair** [comment]
I forked this repository and I configured my fork to buil using AppVeyor.
It was not so difficult for a newcomer.
In this way I can trigger the build when I need.
Now the difficult task: fid how to configure for Clang :-)

**Comment by jpfr** [comment]
LLVM7 is preinstalled on the Appveyor Windows images.

https://www.appveyor.com/docs/windows-images-software/#llvm

**Comment by escherstair** [comment]
I did a lot of test, but I have a problem related to rc.exe that seems not in the path.
A lot of results in google, but no effective solution (up to now).

**Comment by escherstair** [comment]
I asked support to AppVeyor community, because I can't find how to fix this issue.

**Comment by escherstair** [comment]
Good news!
I was able to configure AppVeyor to use clang on Windows.

I can create a pull request, but now sources needs a fix because errors in ua_network_tcp.c.

Can I open a pull request?

**Comment by Pro** [comment]
Cool! Yes, please open a PR and let's see what the issue with `ua_network_tcp.c` is.
Please use `master` as your base branch since there we already implemented some architecture changes to the network layer.

**Comment by escherstair** [comment]
[Here](https://ci.appveyor.com/project/open62541/open62541/builds/20086367/job/47y2gvcgg213nkj5) you can see the errors in ua_network_tcp.c while building with clang.

**Comment by Pro** [comment]
This is due to the fact that the define for UA_SOCKET differs in the int size.
It should be fixed by extending this define:
https://github.com/open62541/open62541/blob/f3cb66a68a388fc143c3199015019265f2151c2a/arch/win32/ua_architecture.h#L68

clang on windows probably does not define __MINGW32__ and thus it takes the else branch, which defines `UA_SOCKET` as `SOCKET`. In general this should be corect, but it looks like there is some magic going on in the background and it should be defined as int.

**Comment by escherstair** [comment]
[Here](https://blog.kowalczyk.info/article/j/guide-to-predefined-macros-in-c-compilers-gcc-clang-msvc-etc..html) is a list of predefined macros in compilers.

@Pro I've just pushed a new commit to PR #2180 to extend the define as you suggested.

**Comment by escherstair** [comment]
@Pro having extended the define didn't fix the error.
Could the issue be related to `fd_set` data type declaration?

**Comment by escherstair** [comment]
@Pro I modified my fix and now the original issue is solved.
But another ones came out

**Comment by jpfr** [comment]
This was merged. Thanks for all the work @escherstair !
