### ISSUE TITLE
MQTT Build failed

### ISSUE THREAD

**Issue by opcua-tsn-team-kalycito** [open62541/open62541#4727]
## Description
MQTT build failed in the latest master.
## Background Information / Reproduction Steps
Compilation error occurs while building the latest open62541 master.

Used CMake options:

```bash
cmake -DUA_ENABLE_EXAMPLES=ON -DUA_ENABLE_PUBSUB=ON -DUA_ENABLE_PUBSUB_MQTT=ON ..
```
The following are error logs,

```
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:212:17: error: conflicting types for ‘mqtt_connect’
  212 | enum MQTTErrors mqtt_connect(struct mqtt_client *client,
      |                 ^~~~~~~~~~~~
In file included from /mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:25:
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.h:1425:17: note: previous declaration of ‘mqtt_connect’ was here
 1425 | enum MQTTErrors mqtt_connect(struct mqtt_client *client,
      |                 ^~~~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c: In function ‘mqtt_connect’:
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:245:13: error: expected ‘)’ before ‘connect_flags’
  245 |             connect_flags, keep_alive
      |             ^~~~~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:191:11: note: in definition of macro ‘MQTT_CLIENT_TRY_PACK’
  191 |     tmp = pack_call;                                                \
      |           ^~~~~~~~~
[ 31%] Building C object CMakeFiles/open62541-plugins.dir/plugins/mqtt/ua_mqtt_adapter.c.o
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:244:17: error: passing argument 9 of ‘mqtt_pack_connection_request’ makes integer from pointer without a cast [-Werror=int-conversion]
  244 |                 caFilePath, caPath, clientCertPath, clientKeyPath
      |                 ^~~~~~~~~~
      |                 |
      |                 const char *
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:191:11: note: in definition of macro ‘MQTT_CLIENT_TRY_PACK’
  191 |     tmp = pack_call;                                                \
      |           ^~~~~~~~~
In file included from /mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:25:
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.h:717:46: note: expected ‘uint8_t’ {aka ‘unsigned char’} but argument is of type ‘const char *’
  717 |                                      uint8_t connect_flags,
      |                                      ~~~~~~~~^~~~~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:244:29: error: passing argument 10 of ‘mqtt_pack_connection_request’ makes integer from pointer without a cast [-Werror=int-conversion]
  244 |                 caFilePath, caPath, clientCertPath, clientKeyPath
      |                             ^~~~~~
      |                             |
      |                             const char *
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:191:11: note: in definition of macro ‘MQTT_CLIENT_TRY_PACK’
  191 |     tmp = pack_call;                                                \
      |           ^~~~~~~~~
In file included from /mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:25:
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.h:718:47: note: expected ‘uint16_t’ {aka ‘short unsigned int’} but argument is of type ‘const char *’
  718 |                                      uint16_t keep_alive);
      |                                      ~~~~~~~~~^~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:240:9: error: too many arguments to function ‘mqtt_pack_connection_request’
  240 |         mqtt_pack_connection_request(
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:191:11: note: in definition of macro ‘MQTT_CLIENT_TRY_PACK’
  191 |     tmp = pack_call;                                                \
      |           ^~~~~~~~~
In file included from /mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:25:
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.h:710:9: note: declared here
  710 | ssize_t mqtt_pack_connection_request(uint8_t* buf, size_t bufsz,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:245:13: error: expected ‘)’ before ‘connect_flags’
  245 |             connect_flags, keep_alive
      |             ^~~~~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:198:15: note: in definition of macro ‘MQTT_CLIENT_TRY_PACK’
  198 |         tmp = pack_call;                                            \
      |               ^~~~~~~~~
[ 34%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_session.c.o
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:244:17: error: passing argument 9 of ‘mqtt_pack_connection_request’ makes integer from pointer without a cast [-Werror=int-conversion]
  244 |                 caFilePath, caPath, clientCertPath, clientKeyPath
      |                 ^~~~~~~~~~
      |                 |
      |                 const char *
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:198:15: note: in definition of macro ‘MQTT_CLIENT_TRY_PACK’
  198 |         tmp = pack_call;                                            \
      |               ^~~~~~~~~
In file included from /mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:25:
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.h:717:46: note: expected ‘uint8_t’ {aka ‘unsigned char’} but argument is of type ‘const char *’
  717 |                                      uint8_t connect_flags,
      |                                      ~~~~~~~~^~~~~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:244:29: error: passing argument 10 of ‘mqtt_pack_connection_request’ makes integer from pointer without a cast [-Werror=int-conversion]
  244 |                 caFilePath, caPath, clientCertPath, clientKeyPath
      |                             ^~~~~~
      |                             |
      |                             const char *
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:198:15: note: in definition of macro ‘MQTT_CLIENT_TRY_PACK’
  198 |         tmp = pack_call;                                            \
      |               ^~~~~~~~~
In file included from /mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:25:
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.h:718:47: note: expected ‘uint16_t’ {aka ‘short unsigned int’} but argument is of type ‘const char *’
  718 |                                      uint16_t keep_alive);
      |                                      ~~~~~~~~~^~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:240:9: error: too many arguments to function ‘mqtt_pack_connection_request’
  240 |         mqtt_pack_connection_request(
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:198:15: note: in definition of macro ‘MQTT_CLIENT_TRY_PACK’
  198 |         tmp = pack_call;                                            \
      |               ^~~~~~~~~
In file included from /mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:25:
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.h:710:9: note: declared here
  710 | ssize_t mqtt_pack_connection_request(uint8_t* buf, size_t bufsz,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/c/Project/test/open62541/plugins/mqtt/ua_mqtt_adapter.c: In function ‘connectMqtt’:
/mnt/c/Project/test/open62541/plugins/mqtt/ua_mqtt_adapter.c:466:29: error: passing argument 8 of ‘mqtt_connect’ makes integer from pointer without a cast [-Werror=int-conversion]
  466 |                             NULL, NULL, NULL, NULL, UA_FALSE, 0, client->keep_alive);
      |                             ^~~~
      |                             |
      |                             void *
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c: At top level:
[ 34%] Building C object CMakeFiles/open62541-plugins.dir/arch/posix/ua_clock.c.o
In file included from /mnt/c/Project/test/open62541/plugins/mqtt/ua_mqtt_adapter.c:10:
/mnt/c/Project/test/open62541/plugins/mqtt/../../deps/mqtt-c/mqtt.h:1432:38: note: expected ‘uint8_t’ {aka ‘unsigned char’} but argument is of type ‘void *’
 1432 |                              uint8_t connect_flags,
      |                              ~~~~~~~~^~~~~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:1081:9: error: conflicting types for ‘mqtt_pack_connection_request’
 1081 | ssize_t mqtt_pack_connection_request(uint8_t* buf, size_t bufsz,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/c/Project/test/open62541/plugins/mqtt/ua_mqtt_adapter.c:466:35: error: passing argument 9 of ‘mqtt_connect’ makes integer from pointer without a cast [-Werror=int-conversion]
  466 |                             NULL, NULL, NULL, NULL, UA_FALSE, 0, client->keep_alive);
      |                                   ^~~~
      |                                   |
      |                                   void *
In file included from /mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:25:
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.h:710:9: note: previous declaration of ‘mqtt_pack_connection_request’ was here
  710 | ssize_t mqtt_pack_connection_request(uint8_t* buf, size_t bufsz,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /mnt/c/Project/test/open62541/plugins/mqtt/ua_mqtt_adapter.c:10:
/mnt/c/Project/test/open62541/plugins/mqtt/../../deps/mqtt-c/mqtt.h:1433:39: note: expected ‘uint16_t’ {aka ‘short unsigned int’} but argument is of type ‘void *’
 1433 |                              uint16_t keep_alive);
      |                              ~~~~~~~~~^~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c: In function ‘mqtt_pack_connection_request’:
/mnt/c/Project/test/open62541/plugins/mqtt/ua_mqtt_adapter.c:465:15: error: too many arguments to function ‘mqtt_connect’
  465 |     mqttErr = mqtt_connect(client, clientId, NULL, NULL, 0, username, password,
      |               ^~~~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:1164:30: error: ‘MQTT_CONNECT_CAFILEPATH’ undeclared (first use in this function)
 1164 |             connect_flags |= MQTT_CONNECT_CAFILEPATH;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /mnt/c/Project/test/open62541/plugins/mqtt/ua_mqtt_adapter.c:10:
/mnt/c/Project/test/open62541/plugins/mqtt/../../deps/mqtt-c/mqtt.h:1425:17: note: declared here
 1425 | enum MQTTErrors mqtt_connect(struct mqtt_client *client,
      |                 ^~~~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:1164:30: note: each undeclared identifier is reported only once for each function it appears in
/mnt/c/Project/test/open62541/plugins/mqtt/ua_mqtt_adapter.c: At top level:
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:1172:30: error: ‘MQTT_CONNECT_CAPATH’ undeclared (first use in this function); did you mean ‘MQTT_CONNECT_PASSWORD’?
 1172 |             connect_flags |= MQTT_CONNECT_CAPATH;
      |                              ^~~~~~~~~~~~~~~~~~~
      |                              MQTT_CONNECT_PASSWORD
cc1: error: unrecognized command line option ‘-Wno-static-in-inline’ [-Werror]
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:1180:30: error: ‘MQTT_CONNECT_CLIENTCERTPATH’ undeclared (first use in this function)
 1180 |             connect_flags |= MQTT_CONNECT_CLIENTCERTPATH;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:1188:30: error: ‘MQTT_CONNECT_CLIENTKEYPATH’ undeclared (first use in this function)
 1188 |             connect_flags |= MQTT_CONNECT_CLIENTKEYPATH;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [CMakeFiles/open62541-plugins.dir/build.make:251: CMakeFiles/open62541-plugins.dir/plugins/mqtt/ua_mqtt_adapter.c.o] Error 1
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:1198:26: error: ‘MQTT_CONNECT_USETLS’ undeclared (first use in this function); did you mean ‘MQTT_CONNECT_USER_NAME’?
 1198 |         connect_flags |= MQTT_CONNECT_USETLS;
      |                          ^~~~~~~~~~~~~~~~~~~
      |                          MQTT_CONNECT_USER_NAME
make[3]: *** Waiting for unfinished jobs....
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:1250:9: error: ‘useTSL’ undeclared (first use in this function); did you mean ‘useTLS’?
 1250 |     if (useTSL) {
      |         ^~~~~~
      |         useTLS
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:1195:13: error: ‘strncpy’ output truncated before terminating nul copying 1 byte from a string of the same length [-Werror=stringop-truncation]
 1195 |             strncpy(strTLS, "1", 1);
      |             ^~~~~~~~~~~~~~~~~~~~~~~
[ 34%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_nodes.c.o
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c:1197:13: error: ‘strncpy’ output truncated before terminating nul copying 1 byte from a string of the same length [-Werror=stringop-truncation]
 1197 |             strncpy(strTLS, "0", 1);
      |             ^~~~~~~~~~~~~~~~~~~~~~~
/mnt/c/Project/test/open62541/deps/mqtt-c/mqtt.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-static-in-inline’ [-Werror]
cc1: all warnings being treated as errors
make[3]: *** [CMakeFiles/open62541-plugins.dir/build.make:225: CMakeFiles/open62541-plugins.dir/deps/mqtt-c/mqtt.c.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:541: CMakeFiles/open62541-plugins.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

## Checklist

Please provide the following information:

 - [X] open62541 Version (release number or git tag): b0dcc9161a234b4c338d564d250dad3878cd44b0
 - [ ] Other OPC UA SDKs used (client or server): 
 - [X] Operating system: Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [X] Self-contained code example attached: tutorial_pubsub_mqtt_publish
 - [ ] Critical issue

**Comment by kimim** [comment]
latest MQTT + CAFILE modification causes problem. I'm looking into it.

**Comment by kimim** [comment]
This issue is fixed in latest 1.3 branch, could you have a try and close this issue?

**Comment by Fischer-Thomas** [comment]
I just checked and i am still getting the same compiler errors as in the original post. (master AND 1.3)
My CMakeFlags are: 
- UA_ENABLE_PUBSUB=On
- UA_ENABLE_PUBSUB_MQTT=On
- UA_ENABLE_MQTT_TLS=On

@kimim @jpfr 
Can you verify this?
